### ISSUE TITLE
Weather: some days return data from the previous day

### ISSUE THREAD

**Issue by aenfield** [awfuldynne/golf_course_project#11]
Per spelunking together, it looks like some requests - at least for Hawaiian locations - give us the data for the previous day, possibly because if we pass our own epoch time - which is two hours ahead of Hawaii in January - the API converts this to Hawaii time, which is on the previous day, and returns 24 hours from the previous day.

One possible fix for this is to switch to using the 'yyyy-mm-ddThh:mm:ss' format (2012-01-05T00:00:00) in the call, instead of the epoch time. I think then the API doesn't do any conversion and treats the date/time as local.

**Comment by awfuldynne** [comment]
Resolved in 95b44d2832899819456d69696236f38a00bb688f
