### ISSUE TITLE
Weather code has path/file issues

### ISSUE THREAD

**Issue by aenfield** [awfuldynne/golf_course_project#16]
The weather test_column_names test fails. You can see this if you run 'python -m unittest' from pygolfdata, or if you look at the output of the Travis build. I took a cut at fixing, but I think there may be more going on than I understand, or I'm confused.

At first I thought it might just be a path issue - the current working dir when tests run is pygolfdata, and the current code uses "../test_data/weather_date_api_test.csv", which I don't think would work because it looks like the path is relative to the weather/tests dir. 

However, when I tried to fix by changing the path to "weather/test_data/weather_date_api_test.csv", the test still failed, w/ the same ValueError. I think the current code, with any path that has a file name, will always raise a ValueError even when the path is valid, because the code checks to see if the path is a directory - since the path has a file at the end, os.path.isdir returns False.

**Comment by awfuldynne** [comment]
Resolved with 479def01326663c488bd1d659038f4e0c8a4cef2
