### ISSUE TITLE
Weather code has a few pylint issues

### ISSUE THREAD

**Issue by aenfield** [awfuldynne/golf_course_project#20]
You're probably already on this, but just to have an issue. The pylint output at https://travis-ci.org/awfuldynne/golf_course_project/builds/381205700 shows a few pylint issues w/ the latest weather code.

**Comment by aenfield** [comment]
Also, if it's just that pylint is getting something wrong w/ imports - I think this may happen sometimes when used w/ tests, because test discovery may be doing addtl stuff w/ the path? After all, the tests run, right? - then you may be able to ignore the specific import-error in test_weather_module w/ code like the following. You'd need to replace the 'no-name-in-module' with 'import-error' and probably add an explanatory comment. The comment w/ 'pylint' applies the exception only to the particular line, so pylint w/ still check for the same issue elsewhere in the file/project, which is what we want.

**
# pylint isn't seeing the shotlink module here, while these tests run fine, so it's a false pos
from data import shotlink # pylint: disable=no-name-in-module
**

**Comment by awfuldynne** [comment]
Fixed in 1b7559d36c83c30c4390dc34b7f5a2f73a9c276a
