### ISSUE TITLE
Extract at least some code from demo notebook

### ISSUE THREAD

**Issue by aenfield** [awfuldynne/golf_course_project#32]
This per Joe's request to keep the notebook shorter/simpler. We could - perhaps? - create a /pygolfdata/notebook/utils.py file and put routines there?

**Comment by reyadji** [comment]
I've ported the TensorFlow model to /pygolfdata/models/tf_linear_regression.py.

**Comment by aenfield** [comment]
Folks fixed this w/ things like vis_tools.py.
