### ISSUE TITLE
Make hyperlinks consistent and add updated file list in readme

### ISSUE THREAD

**Issue by aenfield** [awfuldynne/golf_course_project#35]

**Comment by awfuldynne** [comment]
Could you give more of a description of how the hyperlinks should be formatted? I can fix this tomorrow.

**Comment by aenfield** [comment]
Fixed with 342324f8c19db9286e84874253a559bef003398f and a few before it.

**Comment by aenfield** [comment]
It was minor stuff I was just tracking there so I wouldn’t forget. I did it.


On June 2, 2018 at 10:29:03 PM, Sean Miller (notifications@github.com)
wrote:

Could you give more of a description of how the hyperlinks should be
formatted? I can fix this tomorrow.

—
You are receiving this because you authored the thread.
Reply to this email directly, view it on GitHub
<https://github.com/awfuldynne/golf_course_project/issues/35#issuecomment-394138253>,
or mute the thread
