### ISSUE TITLE
Remove api key from geocoding.py

### ISSUE THREAD

**Issue by aenfield** [awfuldynne/golf_course_project#5]
I just noticed that geocoding.py has an API key in the file. You probably want to remove this, so it's not publicly accessible for anyone looking at GitHub?

One approach is to change the code so that it reads the key from an environment variable (import os and then os.environ['MY_VAR']) and set the environment variable before you run the code.

Also, even if you remove the key from the file and check in a new version of the file w/o the key, I think the key may still be accessible - it's still in the Git history for the file. You might want to deactivate the key somehow, so it's no longer usable?

**Comment by reyadji** [comment]
I usually use `git rebase -i origin/master` and then squash that specific commit to erase the API from git history.

**Comment by ucalegon206** [comment]
I may have not pushed the change to remove the key. I'll do that after I'm
done judging this jump rope competition...

**Comment by ucalegon206** [comment]
Resolving, closed, put to bed, fixed issue #5 by recommitting the file without the api_key
